### PR TITLE
On Stream Chat Spoiler Code

### PR DESCRIPTION
**Pull request by WhiteNervosa**
https://streamable.com/k3t5v
To fix https://github.com/MemeLabs/chat-gui/issues/113

### CODE REVIEW

**Comment by xDashh** [comment]
How does this behave with lines like 
`normal text || long spoiler text || normal text again` ?
Moving the trailing text around a long might look a bit awkward - any other opinions?

**Comment by WhiteNervosa** [comment]
From my understanding, and it makes sense, is that it looks quite ugly to have just black bars on the screen with no context rather than a shorter one that informs you it is a spoiler. I think the current implementation on the regular chat is better done.
spoiler

**Comment by xDashh** [comment]
Ah, yeah that makes sense. If it works well in the case I described above (i.e. moves the text properly), then it looks good to me.

**Comment by jbpratt78** [comment]
> How does this behave with lines like
> `normal text || long spoiler text || normal text again` ?
> Moving the trailing text around a long might look a bit awkward - any other opinions?
> 
> Oh, I missed that this is only intended for onstreamchat - why should it behave differently there? (or was it intended for regular chat too?)

@WhiteNervosa can you show a few images/examples of longer cases such as the one here involving the long spoiler opening up and moving the text after it? Though these are strange cases, we have a special group. Pending this, we can merge.

**Comment by WhiteNervosa** [comment]
Absolutely - similar to https://github.com/MemeLabs/chat-gui/issues/121 I haven't actually implemented these other than trying to help out Strims, after implementing them or booting up a dev chat I can start making them much cleaner and without issue.

**Comment by WhiteNervosa** [comment]
Changing the code to:
`.spoiler:before {
    content: "[SPOILER]";
    z-index: 1;
    font-size: small;
    color: #828282;
    font-weight: 500;
    padding-left: 0.3em;
    position: absolute;
    display: block;
    background: #222;
    width: 75px;
    height: 22px;
}

 .msg-chat .spoiler {
    display: inline-block;
    width: 80px;
    height: 25px;
    position: relative;
    top: 6px;
    overflow: hidden;
}`

Fixes all of the prior issues of it being placed anywhere in the message.
e1yCaR0

**Comment by xDashh** [comment]
indentation seems off (needs another level). right? Otherwise if the feature is tested, looks good and can merge.

**Comment by WhiteNervosa** [comment]
Do you mean from the start of chat? That is simply the style we went for names on screen, pardon.

**Comment by xDashh** [comment]
Oh sorry, I totally missed this. I meant indentation in the CSS code :sweat_smile:

**Comment by jbpratt78** [comment]
[STALE] Shelving for now. Thank you for the feature!

**Pull request closed without merging**
