### PR TITLE
adding emote: PeepoBird

### PR DESCRIPTION
**Pull request by Oreganon**

### CODE REVIEW

**Comment by slugalisk** [comment]
duplicates miyanoBird

**Comment by slugalisk** [comment]
is there a version fo this that isn't so blurry?

**Comment by Oreganon** [comment]
No idea what you are talking about, its exactly like PeepoWierd https://i.imgur.com/X5YLb0R.png

**Comment by slugalisk** [comment]
PeepoWeird is blurry too

**Pull request closed without merging**
