### PR TITLE
Style update

### PR DESCRIPTION
**Pull request by JoannesJ**
Closes issue #38

### CODE REVIEW

**Comment by xDashh** [comment]
Commenting as i look over it
- for license not sure if we can just remove something in that way.

- for flair https://github.com/MemeLabs/chat-gui/pull/40/files#diff-7391afddf999a0bd5912af196db789d1R12 is there a better way so we don't have to deal with it in the future? Not sure why the blank space is displayed atm, can't we check if some flair/role has an icon assigned, and if not, skip it entirely? (not familiar with that part of the code at all)

**Comment by JoannesJ** [comment]
Yeah, I might have been a bit too hasty with the licenses, hehehe.
I'll put the first one back.
The other one though, is about a graphic that isn't in the project.

About the flair; I thought we were just looking for a quick fix.
But I'll take a look.
It is something that would be used in the future?

**Comment by JoannesJ** [comment]
Ok, all fixed now.

@KenanY Yeah, I snuck some tabs in there. It's fixed now.
Also added an extra var to `common`. But the rest just seems to specific to merit a var.

**Comment by xDashh** [comment]
Thanks! Merged by https://github.com/MemeLabs/chat-gui/commit/f9997aae31659f73f86d4345207cfe11ed1b7a10
Will have to see how people react to the new layout. Change is spooky, especially after having used another layout for many years.

**Pull request closed without merging**
