### PR TITLE
clickable viewerstate functionality and more mockstream tests

### PR DESCRIPTION
**Pull request by Abeous**
when a.user is clicked while CTRL is held it opens new tab with the user's viewer state
https://i.imgur.com/si80Y0F.gifv
if user has no viewerstate nothing happens, naturally

### CODE REVIEW

**Comment by jbpratt78** [comment]
I think I am a bit confused, does this open what the user is currently watching? (their viewerstate) or does this open what the user has set as their stream in the profile?

**Comment by Abeous** [comment]
this opens what the user is currently watching, so if you hover over a users nickname and decide you want to watch what they are watching this makes it much easier than manually typing

**Comment by slugalisk** [comment]
@Abeous instead of replacing the current behavior (click to highlight the user in chat... i use this constantly) can you add a context menu on left click and put the link to new link there? we could also support normal left click by publishing a message to the parent frame. i can help implement this if you want.

**Comment by slugalisk** [comment]
while the context menu is open it might be good to freeze chat autoscrolling... i think this is implemented already for another feature.

**Pull request merged**
