### PR TITLE
add setting for infinite animated png loop

### PR DESCRIPTION
**Pull request by KenanY**
- [x] apply setting retroactively to old messages
  - [x] test on Chrome

Closes https://github.com/MemeLabs/chat-gui/issues/13

### CODE REVIEW

**Comment by xDashh** [comment]
Chrome support has been reported as working well so far.
For retroactive applying it would have to be re-checked.

**Comment by xDashh** [comment]
GitHub tells me this needs some adjustments since the new PR got merged, otherwise I don't remember any reason not to merge :thinking: @KenanY

**Comment by KenanY** [comment]
Yeah gotta make it work with the new changes to `assets/chat/js/formatters.js`.

**Comment by xDashh** [comment]
Because of merge-conflicts that existed by now, I copied most of the relevant code into https://github.com/MemeLabs/chat-gui/commit/67cd2d175fd89bb82ba5297a6256a64f40989a29 and hopefully correctly added generify-compatibility on top of it. Thanks!

**Pull request closed without merging**
