### PR TITLE
Properly hide autocomplete results when disabled

### PR DESCRIPTION
**Pull request by atomicfish1234**
Fixes two issues that occur when autocomplete is disabled:
1. Autocomplete results no longer briefly flash after the user starts typing
2. ~~Users can no longer tab through autocomplete results~~ (removed from PR on 9/26)

Related issue: https://github.com/MemeLabs/chat-gui/issues/355

### CODE REVIEW

**Comment by slugalisk** [comment]
we can't use display because the transition delay is used to debounce the menu so it doesn't flicker while users are typing and display can't be controlled with transition.

**Comment by atomicfish1234** [comment]
Thanks for pointing that out. My understanding is that debouncing is handled by the keyframe animation. When text is entered, display: initial is immediately applied to the autocomplete div, but the results remain invisible for 540ms, when we reach the 90% point in the keyframe animation and opacity changes to 1. So, as far as I can tell, debouncing was not regressed.

The transition serves to fade out the opacity over a 250ms period when we hide results (either because the 15-second timeout has completed or we have run out of matches given the input text). Consequently, the regression seems to be that the fadeout no longer exists - results are hidden immediately.

Given that, I have reverted back to using opacity. The downside is that if a user disables autocomplete while results are displayed, the results will be hidden but clickable until either the 15-second timeout elapses or the user interacts with the text box. That seems like an extreme edge case though, so I'm not worried about it.

**Comment by atomicfish1234** [comment]
I'm realizing I might be doing the wrong thing with this change... Is the purpose of the "Auto-complete helper" setting to enable/disable autocomplete entirely, or is it just meant to show/hide the autocomplete suggestions while still allowing users to tab through the results? I had thought it was the former, but now I'm thinking it might be the latter.

**Comment by slugalisk** [comment]
i don't know what the original intent was and the person who wrote this has been gone for a long time. no one has complained about the current behavior and removing it may be disruptive.

**Comment by atomicfish1234** [comment]
I see. I have removed that change. Sorry about that.

In the latest set of changes, the flashing issue is fixed, and autocomplete results are tabbable when the setting is disabled. These changes also fix an issue where invisible results are clickable when the setting is disabled.

**Review by slugalisk — APPROVED** [review]
no worries. thanks for working on this. lgtm 👍

**Pull request merged**
