### PR TITLE
Added emote context menu for crediting people that create emotes

### PR DESCRIPTION
**Pull request by ftwpala**
Feedback appreciated

https://i.imgur.com/flyP647.gif

Please do not merge if PR is accepted, contact me first as i have to do some additional gruntwork regarding the Authors of emotes

Related to issue https://github.com/MemeLabs/chat-gui/issues/460

### CODE REVIEW

**Comment by slugalisk** [comment]
this looks good for the most part but we also have holiday variants for december. could the alternate creator thing be extended to support this?

**Comment by ftwpala** [comment]
https://i.imgur.com/eFSjsy4.gif changed the background color a little bit. 

Thanks to @Abeous for feedback  about UI and suggestion regarding json restructuring

**Comment by slugalisk** [comment]
i hate nit picking naming but can we just call the seasonal variants "october" and "december" like we do elsewhere in the project? once that's fixed i'll merge

**Comment by ftwpala** [comment]
Credits to Namemannen for suggesting the idea of a second listener for a more robust design that is not reliant on the HTML

**Comment by ftwpala** [comment]
Please do not merge before i fill in the author names

**Comment by ftwpala** [comment]
Merge ready, going to collect data on people who say "I made this" and update it after some time

**Pull request merged**
