### PR TITLE
fix flip css

### PR DESCRIPTION
**Pull request by SoMuchForSubtlety**
fixes https://github.com/MemeLabs/chat-gui/issues/85

### CODE REVIEW

**Comment by SoMuchForSubtlety** [comment]
nevermind, only works on the first message.

**Comment by xDashh** [comment]
I think the solution we are looking for is giving the flip-css a z-index, but I haven't looked at relevant code.

**Comment by SoMuchForSubtlety** [comment]
I tried that too, doesn't work either.

**Comment by KenanY** [comment]
Removing myself since it sounds like this isn't complete yet? Feel free to re-add me if I'm wrong 😄

**Comment by jbpratt78** [comment]
[STALE] Shelving for now. Thank you for the feature!

**Pull request closed without merging**
