### PR TITLE
Preview emotes within autocomplete results

### PR DESCRIPTION
**Pull request by atomicfish1234**
Emotes are now displayed inline with autocomplete results. There is also a setting to enable/disable this feature.

Animated emotes are improperly offset in dev-chat, but I think that issue might be unique to dev-chat.

### CODE REVIEW

**Comment by slugalisk** [comment]
this is deployed to test chat https://chat2.strims.gg/

there is a layout issue (it the images overflow the autocomplete menu) but idk if this is the issue you described. https://i.imgur.com/gEms2cr.png

**Comment by atomicfish1234** [comment]
The offset issue that I mentioned doesn't repro in test chat, so I think we're good on that front. This is what it looks like in dev chat: https://i.imgur.com/pObMv5w.png

The emote overflow that you screenshotted was actually intentional. Without the overflow, the tops of the emotes get chopped off, so they look wrong. I thought about increasing the heights of the results instead of allowing overflow, but that didn't seem ideal because (1) non-emote results would have needlessly increased heights, (2) it would increase the amount of chat that is obscured by the results, and (3) we would have to maintain the height if taller emotes were to be added in the future. Emotes already overflow a bit in chat messages, so I thought it would be ok, but I am open to ideas.

By the way, I pushed a change shortly after I created this PR, but it doesn't look like that change made it to test chat: https://github.com/MemeLabs/chat-gui/pull/354/commits/c9cc6782d2387d607083b14c8a57c4c59f84ddb8

**Comment by slugalisk** [comment]
instead of overflowing the menu can we shrink the emotes 50% like this https://i.imgur.com/y5z1Uvi.png

**Comment by atomicfish1234** [comment]
Done. I went with a 60% scale because that looks to be about the biggest size that can fit into the menu without overflowing.

The wider emotes were surrounded by a noticeable amount of empty space after scaling, so I added some custom styling to fix that.

PepeLaugh has a strange issue where it initially appears at full size and then quickly scales down to the expected size. Might be another artifact of dev chat?

**Review by slugalisk — APPROVED** [review]
lgtm. thanks for adding this 👍

**Pull request merged**
